import EnvConfig from 'react-native-config';

export const Config = {
  KAKAO_LOGIN_CLIENT_ID: EnvConfig.EXPO_PUBLIC_KAKAO_LOGIN_CLIENT_ID,
  KAKAO_LOGIN_REDIRECT_URI: EnvConfig.EXPO_PUBLIC_KAKAO_LOGIN_REDIRECT_URI,
  API_URL: EnvConfig.EXPO_PUBLIC_API_URL,
  NAVER_LOGIN_CLIENT_ID: EnvConfig.EXPO_PUBLIC_NAVER_LOGIN_CLIENT_ID,
  NAVER_LOGIN_REDIRECT_URI: EnvConfig.EXPO_PUBLIC_NAVER_LOGIN_REDIRECT_URI,
  INVITATION_URL: EnvConfig.EXPO_PUBLIC_INVITATION_URL,
  APPLE_LOGIN_CLIENT_ID: EnvConfig.EXPO_PUBLIC_APPLE_LOGIN_CLIENT_ID,
  APPLE_LOGIN_REDIRECT_URI: EnvConfig.EXPO_PUBLIC_APPLE_LOGIN_REDIRECT_URI,
  MODE: EnvConfig.EXPO_PUBLIC_MODE,
};
