const a = {
  message: 'Network Error',
  name: 'AxiosError',
  stack:
    'AxiosError: Network Error\n    at handleError (http://127.0.0.1:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:161093:39)\n    at call (native)\n    at dispatchEvent (http://127.0.0.1:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:14296:31)\n    at setReadyState (http://127.0.0.1:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:13505:33)\n    at __didCompleteResponse (http://127.0.0.1:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:13329:29)\n    at apply (native)\n    at anonymous (http://127.0.0.1:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:13442:124)\n    at apply (native)\n    at emit (http://127.0.0.1:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:15107:40)\n    at apply (native)\n    at anonymous (http://127.0.0.1:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:15036:200)\n    at emit (http://127.0.0.1:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:15050:62)\n    at ?anon_0_ (http://127.0.0.1:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:159415:64)\n    at throw (native)\n    at asyncGeneratorStep (http://127.0.0.1:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:5548:19)\n    at _throw (http://127.0.0.1:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=app&unstable_transformProfile=hermes-stable:5565:29)\n    at tryCallOne (address at InternalBytecode.js:1:1180)\n    at anonymous (address at InternalBytecode.js:1:1874)',
  config: {
    transitional: {silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false},
    adapter: ['xhr', 'http', 'fetch'],
    transformRequest: [null],
    transformResponse: [null],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: {},
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'multipart/form-data',
      'X-KBOAPP-TOKEN': 'i6fhBq8lMx09bVMxZtlLox04ngfOAy',
    },
    baseURL: 'https://kboapp.xyz',
    method: 'post',
    url: '/tickets/ticket_add/',
    data: {
      _parts: [
        [
          'image',
          {
            uri: 'file:///data/user/0/xyz.kboapp/cache/71dbd4fe-d7c0-47a7-ae84-f5f4db669551.PNG',
            type: 'image',
            name: 'file:///data/user/0/xyz.kboapp/cache/ImagePicker/926c2e2f-eb0c-4977-aff7-f11726bdda7e.jpeg',
          },
        ],
        ['date', '2025-03-27'],
        ['game', '696'],
        ['result', '무승부'],
        ['weather', '비'],
        ['is_ballpark', 'true'],
        ['score_our', '2'],
        ['score_opponent', '2'],
        ['starting_pitchers', '왜'],
        ['gip_place', '잠실야구장'],
        ['food', '냐'],
        ['memo', '고'],
        ['is_homeballpark', 'false'],
        ['only_me', 'true'],
        ['is_double', 'false'],
        ['hometeam_id', '3'],
        ['awayteam_id', '8'],
        ['direct_yn', 'false'],
        ['is_cheer', 'true'],
      ],
    },
    allowAbsoluteUrls: true,
  },
  code: 'ERR_NETWORK',
}
